frames: []

epochs-autoenc: 150
epochs-pre-pred: 0
epochs-dec: 100
epochs-dist: 300

# generate previews every x epochs
prev-period: 10
tgt-update-period: 999
proba-update-period: 999
cp-period: 2

# optimizer
lr-dist: 1e-4
lr-autoenc: 1e-4
lr-assign: 1e-4
decay : 2e-4
lr-power : 0.99
momentum: 0.9

# foreground prediction
lambda-: 1
# image reconstruction
gamma: 0
# pairwise similarity
beta: 0.1
# clustering
alpha: 0
delta: 1000

# batch
batch-size: 2
batch-norm: True

# dataloader
n-segments-test: 300
delta-segments-test: 0
n-segments-train: 700
delta-segments-train: 300
n-workers: 0
cuda: False
n-ims-test: 5

# network input size
in-shape: 512
n-frames-epoch: 100

# augmentation
aug-noise: 0.1
aug-blur-color-low: 100
aug-blur-color-high: 250
aug-blur-space-low: 100
aug-blur-space-high: 250
aug-gamma-low: 0.5
aug-gamma-high: 2.0
aug-flip-proba: 0.5
aug-some: 2
aug-scale: 0.3
aug-rotate: 10.
aug-shear: 20.

# sampling
n-edges-ratio: 0.05
nn-radius: 0.1

n-clusters: 15
embedded-dims: 15

roi-output-size: 1
roi-spatial-scale: 1.0

with-agglo: False
with-pck: False
with-flow: False
reduc-method: 'pca'
ml-up-thr: 0.5
ml-down-thr: 0.5
bag-t: 300
bag-n-feats : 0.1
bag-max-depth : 5

linkage: 'ward'
backbone: 'unet'

thr-assign: 0.001
