precomp-dir : 'precomp_desc'
precomp-desc-path : ''
locs-dir : 'gaze-measurements'
truth-dir : 'ground_truth-frames'
exp-name : 'exp'
frame-prefix : 'frame_'
frame-extension : '.png'
frame-dir : 'input-frames'
csv-fname : 'video1.csv'

# Descriptors/codebooks ready-to-load.
feats-dir : 'precomp_descriptors'

# Superpixel segmentation
slic-compactness : 20.0
slic-size : 1000
slic-n-sp : 1200
slic-rel-size : 0.1

# Superpixel transitions
# sp-trans-init-mode : 'overlap'
sp-trans-init-mode : 'radius'
sp-trans-init-radius : 0.08

# Optical flow
oflow-alpha : 0.012
oflow-ratio : 0.75
oflow-min-width : 50.
oflow-outer-iters : 7
oflow-inner-iters : 1
oflow-sor-iters : 30

n-iters-ksp : 1

monitor-score : False

# Bagging---------------
bag-t : 500
bag-n-bins : 100
bag-n-feats : 0.05
bag-max-samples : 1000
bag-max-depth : 5
bag-jobs : 1
#-----------------------

use-hoof : True
hoof-tau-u : -1 # set to -1 to disactivate!
hoof-n-bins: 100

# Metric learning
n-comp-pca : 3
lfda-k : 7
lfda-dim : 10
ml-n-samps : 6000
ml-up-thr : 0.7
ml-down-thr : 0.3
ml-sigma : 1
ml-embedding : 'orthonormalized'
pca : False  #Overrides LFDA and computes PCA with n-components:lfda-dims

# Graph parameters
norm-neighbor : 0.02
norm-neighbor-in : 0.08
thr-entrance : 0.8

pm-thr : 0.5  #Threshold on KSP+SS PM for positives selection
