aug_blur: 1.0
aug_flip_proba: 0.5
aug_gamma: 0.05
aug_noise: 0.1
aug_rotate: 5.0
aug_scale: 0.3
aug_shear: 12.5
aug_some: 2
batch_norm: true
batch_size: 2
beta: 0.8
cuda: false
data_type: null
decay: 4.0e-05
delta_segments_test: 0
delta_segments_train: 300
ds_shuffle: null
ds_split: null
epochs_all: 100
epochs_autoenc: 30
epochs_dec: 10
epochs_dist: 10
exp_name: ''
frames: null
gamma: 0.8
in_root: /home/ubelix/lejeune/data/medical-labeling
in_shape: 600
lr: null
lr_assign: 0.01
lr_autoenc: 0.001
lr_dist: 0.01
lr_power: 0.9
momentum: 0.9
n_clusters: 10
n_edges: 100
n_frames_epoch: 100
n_ims_test: 5
n_patches: null
n_segments_test: 300
n_segments_train: 700
n_workers: 0
out_dir: /home/ubelix/lejeune/runs/siamese_dec
prev_period: 5
roi_output_size: 1
roi_spatial_scale: 1.0
run_dir: Dataset00
sp_pooling_max: false
train_dir: '00'
v: false
with_flow: true
with_pck: true
