frames: []

epochs-autoenc: 150
epochs-pred: 100
epochs-pre-pred: 20
epochs-dec: 100
epochs-dist: 80

# generate previews every x epochs
prev-period: 10
tgt-update-period: 999
cc-update-period: 10
prior-period: 1
cp-period: 5
unlabeled-period: 10
unlabeled-ratio: 0.15
nnpu-ascent: False
aug-in-neg: False
aug-reset: False
pred-init-dir: ''
pxls: False

aug-method: 'set'
neg-mode: single
loss-obj-pred: 'pu'

phase: 0

# optimizer
lr1: 1e-2
lr2: 1e-3
lr-gamma : 0.1
lr-autoenc: 1e-4
lr-assign: 1e-4
decay : 2e-4
lr-power : 0.99
lr-epoch-milestone-0 : 50
lr-epoch-milestone-1 : 100
momentum: 0.9

# prior estimation
pi-mul: 1.0
init-pi: 0.20
pi-xi: 0.005
pi-overspec-ratio: 1.5
pi-post-ratio: 1.2
pi-min: 0.005
pi-gamma: 0.1
pi-alpha: 1.0
pi-eta: 1.
rho-pi-err: 999
var-thr: 0.005
var-epc: 5
min-var-epc: 30
loc-prior: False

# batch
batch-size: 2
batch-norm: True

# dataloader
cuda: False
n-ims-test: 5

# network input size
in-shape: 512
n-frames-epoch: 100

# augmentation
aug-noise: 0.06
aug-blur-color-low: 100
aug-blur-color-high: 150
aug-blur-space-low: 100
aug-blur-space-high: 150
aug-gamma-low: 1.0
aug-gamma-high: 2.0
aug-flip-proba: 0.5
aug-some: 2
aug-scale: 0.3
aug-rotate: 10.
aug-shear: 20.

reduc-method: 'pca'
ml-up-thr: 0.5
ml-down-thr: 0.5
bag-t: 600
bag-n-feats : 0.1
bag-max-depth : 50

pi-filt-size: 0.05
pi-filt: False
true-prior: False

coordconv: False

# kalman filter
trans-fac: 0.05
obs-fac: 10
xi-fac-start: 0.01
xi-fac-end: 0.03
